import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/header";
import Footer from "@/components/footer";
import "bootstrap/dist/css/bootstrap.min.css";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});
// console.log(roboto);
//server component
export const metadata = {
  // title: "Front App Aswan",
  title: {
    template: "%s -Front App Aswan ",
    default:'Front App Aswan'
  },

  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NavBar />
        <div className="m-5">{children}</div>

        <Footer />
      </body>
    </html>
  );
}
